import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip as RechartsTooltip } from 'recharts';
import { Leaf, Car, Zap, ShoppingBag, Info, Target, Globe2 } from 'lucide-react';
import ChartTooltip from '../components/ChartTooltip';

const pieData = [
  { name: 'Transport', value: 40, color: '#3b82f6' },
  { name: 'Food', value: 25, color: '#10b981' },
  { name: 'Energy', value: 20, color: '#eab308' },
  { name: 'Shopping', value: 15, color: '#a855f7' }
];

const beginnerActions = [
  { title: 'Transport', desc: 'Try carpooling or taking public transit once a week.', icon: Car, color: 'text-blue-400' },
  { title: 'Food', desc: 'Swap one meat-based meal for a plant-based option weekly.', icon: Leaf, color: 'text-emerald-400' },
  { title: 'Energy', desc: 'Switch off lights and unplug appliances when not in use.', icon: Zap, color: 'text-yellow-400' },
  { title: 'Shopping', desc: 'Buy second-hand clothes or repair old ones instead of buying new.', icon: ShoppingBag, color: 'text-purple-400' }
];

const PercentTooltip = (props) => <ChartTooltip {...props} unit="%" />;

const Learn = () => {
  return (
    <div className="max-w-5xl mx-auto py-8 space-y-12 animate-in fade-in duration-500">
      {/* Hero Section */}
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold text-slate-100">What is a Carbon Footprint?</h1>
        <p className="text-lg text-slate-400 max-w-3xl mx-auto leading-relaxed">
          Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. It encompasses everyday choices like how we travel, what we eat, the energy we use at home, and the goods we buy.
        </p>
      </div>

      {/* Stats Bar */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg flex items-center space-x-4">
          <div className="bg-blue-500/20 p-3 rounded-full">
            <Info className="w-8 h-8 text-blue-400" />
          </div>
          <div>
            <p className="text-slate-400 text-sm font-medium">Average Indian</p>
            <p className="text-2xl font-bold text-slate-100">1.9 <span className="text-base font-normal text-slate-500">tonnes/yr</span></p>
          </div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg flex items-center space-x-4">
          <div className="bg-purple-500/20 p-3 rounded-full">
            <Globe2 className="w-8 h-8 text-purple-400" />
          </div>
          <div>
            <p className="text-slate-400 text-sm font-medium">Global Average</p>
            <p className="text-2xl font-bold text-slate-100">4.7 <span className="text-base font-normal text-slate-500">tonnes/yr</span></p>
          </div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg flex items-center space-x-4">
          <div className="bg-emerald-500/20 p-3 rounded-full">
            <Target className="w-8 h-8 text-emerald-400" />
          </div>
          <div>
            <p className="text-slate-400 text-sm font-medium">Paris Target</p>
            <p className="text-2xl font-bold text-slate-100">&lt; 2 <span className="text-base font-normal text-slate-500">tonnes/yr</span></p>
          </div>
        </div>
      </div>

      {/* Category Breakdown & Donut Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-slate-100">Where do emissions come from?</h2>
          <div className="space-y-4">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex items-start space-x-4">
              <Car className="w-6 h-6 text-blue-400 mt-1" />
              <div>
                <h3 className="font-semibold text-slate-200">Transport</h3>
                <p className="text-sm text-slate-400 mt-1">Driving, flying, and public transit. A 10km petrol car trip emits ~2.1 kg CO₂.</p>
              </div>
            </div>
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex items-start space-x-4">
              <Leaf className="w-6 h-6 text-emerald-400 mt-1" />
              <div>
                <h3 className="font-semibold text-slate-200">Food</h3>
                <p className="text-sm text-slate-400 mt-1">Meat production, transportation, and food waste. One beef meal emits ~6.0 kg CO₂.</p>
              </div>
            </div>
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex items-start space-x-4">
              <Zap className="w-6 h-6 text-yellow-400 mt-1" />
              <div>
                <h3 className="font-semibold text-slate-200">Energy</h3>
                <p className="text-sm text-slate-400 mt-1">Electricity, heating, and cooling your home. Running an AC for 1 hour emits ~1.0 kg CO₂.</p>
              </div>
            </div>
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex items-start space-x-4">
              <ShoppingBag className="w-6 h-6 text-purple-400 mt-1" />
              <div>
                <h3 className="font-semibold text-slate-200">Shopping</h3>
                <p className="text-sm text-slate-400 mt-1">Manufacturing and shipping goods. Buying a new piece of clothing emits ~10.0 kg CO₂.</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg flex flex-col items-center justify-center">
          <h2 className="text-lg font-semibold text-slate-200 mb-6">Typical Personal Emission Split</h2>
          <div className="h-72 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={pieData}
                  cx="50%"
                  cy="50%"
                  innerRadius={70}
                  outerRadius={100}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {pieData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <RechartsTooltip content={PercentTooltip} />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="flex flex-wrap justify-center gap-4 mt-6">
            {pieData.map(item => (
              <div key={item.name} className="flex items-center space-x-2">
                <div className="w-3 h-3 rounded-full" style={{ backgroundColor: item.color }} />
                <span className="text-sm text-slate-300">{item.name} ({item.value}%)</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* What Can I Do */}
      <div>
        <h2 className="text-2xl font-bold text-slate-100 mb-6">What can I do? Start here:</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {beginnerActions.map((action, idx) => {
            const Icon = action.icon;
            return (
              <div key={idx} className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-lg relative overflow-hidden group hover:border-slate-700 transition-colors">
                <div className="mb-4">
                  <Icon className={`w-8 h-8 ${action.color}`} />
                </div>
                <h3 className="font-semibold text-slate-200 mb-2">{action.title}</h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  {action.desc}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default Learn;
